// Game Configuration
export const CONFIG = {
    TRACK_WIDTH: 18,
    TRACK_LENGTH: 15000,
    GRASS_WIDTH: 220,
    CAMERA_FOV: 75,
    CAMERA_NEAR: 0.1,
    CAMERA_FAR: 1000,
    AMBIENT_LIGHT_INTENSITY: 0.6,
    DIRECTIONAL_LIGHT_INTENSITY: 1,
    OBSTACLE_SPAWN_INTERVAL: 2000, // milliseconds
    FUEL_SPAWN_INTERVAL: 5500, // milliseconds
    INITIAL_FUEL: 100,
    FUEL_CONSUMPTION_RATE: 0.04,
    FUEL_COLLECTION_BONUS: 15,
    COLLISION_THRESHOLD: 2
  };